[colors.bright]
#black = "#292A2B"
blue = "#64a8d8"
cyan = "#65cedc"
green = "#b6da74"
magenta = "#bc82d3"
red = "#d95473"
white = "#ebf6f5"
yellow = "#e7ca62"

[colors.normal]
#black = "#1d1f21"
blue = "#277AB6"
cyan = "#32B5C7"
green = "#7CBD27"
magenta = "#AD4ED2"
red = "#CF3746"
white = "#d8e2e1"
yellow = "#ECBD10"

[colors.primary]
#background = "#292A2B"
#foreground = "#AEB7B6"

[env]
TERM = "xterm-256color"
EDITOR = "/usr/bin/vim"

[window]
decorations = "buttonless"
dynamic_padding = true
padding.x = 0
padding.y = 0

[font]
size = 11.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[terminal]

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"
